// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $ContagemIsland from "./islands/ContagemIsland.tsx";
import * as $ListaPresentesIsland from "./islands/ListaPresentesIsland.tsx";
import * as $MoneyGIftIsland from "./islands/MoneyGIftIsland.tsx";
import * as $TimelineViduIsland from "./islands/TimelineViduIsland.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/ContagemIsland.tsx": $ContagemIsland,
    "./islands/ListaPresentesIsland.tsx": $ListaPresentesIsland,
    "./islands/MoneyGIftIsland.tsx": $MoneyGIftIsland,
    "./islands/TimelineViduIsland.tsx": $TimelineViduIsland,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
